service: store-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    STAGE: ${sls:stage}
    TABLE_PREFIX: xdopestore-api-${sls:stage}-

plugins:
  - serverless-python-requirements

functions:
  ${file(homepage/service.yml):functions}

resources:
  Resources:
    ${file(homepage/service.yml):resources.Resources}

