functions:
  getConfig:
    handler: homepage/handler.get_config
    events:
      - http:
          path: homepage/config
          method: get
          cors: true

  getVersions:
    handler: homepage/handler.get_versions
    events:
      - http:
          path: homepage/config/versions
          method: get
          cors: true

  updateConfig:
    handler: homepage/handler.update_config
    events:
      - http:
          path: homepage/config
          method: put
          cors: true

  deleteConfig:
    handler: homepage/handler.delete_config
    events:
      - http:
          path: homepage/config
          method: delete
          cors: true

resources:
  Resources:
    HomepageConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_PREFIX}HomepageConfig
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: version
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
