name: Deploy Serverless Services

on:
  push:
    branches:
      - main
    paths:
      - 'homepage/**'

jobs:
  deploy-homepage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: homepage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r ../requirements.txt

      - name: Install Serverless
        run: npm install -g serverless

      - name: Echo instead of Deploy Homepage API
        run: echo "Skipping deployment of Homepage API until AWS is configured"
        # run: sls deploy --stage prod
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: Deploy Homepage API
#        run: sls deploy --stage prod
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
